// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: ping.proto

package ProtoMsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMD_SERVICE int32

const (
	CMD_SERVICE_INIT_SERVICE      CMD_SERVICE = 0
	CMD_SERVICE_G2S_DATA_TRANSFER CMD_SERVICE = 20003
	CMD_SERVICE_S2G_DATA_TRANSFER CMD_SERVICE = 20004
)

// Enum value maps for CMD_SERVICE.
var (
	CMD_SERVICE_name = map[int32]string{
		0:     "INIT_SERVICE",
		20003: "G2S_DATA_TRANSFER",
		20004: "S2G_DATA_TRANSFER",
	}
	CMD_SERVICE_value = map[string]int32{
		"INIT_SERVICE":      0,
		"G2S_DATA_TRANSFER": 20003,
		"S2G_DATA_TRANSFER": 20004,
	}
)

func (x CMD_SERVICE) Enum() *CMD_SERVICE {
	p := new(CMD_SERVICE)
	*p = x
	return p
}

func (x CMD_SERVICE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMD_SERVICE) Descriptor() protoreflect.EnumDescriptor {
	return file_ping_proto_enumTypes[0].Descriptor()
}

func (CMD_SERVICE) Type() protoreflect.EnumType {
	return &file_ping_proto_enumTypes[0]
}

func (x CMD_SERVICE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CMD_SERVICE.Descriptor instead.
func (CMD_SERVICE) EnumDescriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{0}
}

type CMD_GAME int32

const (
	CMD_GAME_INIT_GAME CMD_GAME = 0
	CMD_GAME_PING      CMD_GAME = 1001
	CMD_GAME_PONG      CMD_GAME = 1002
)

// Enum value maps for CMD_GAME.
var (
	CMD_GAME_name = map[int32]string{
		0:    "INIT_GAME",
		1001: "PING",
		1002: "PONG",
	}
	CMD_GAME_value = map[string]int32{
		"INIT_GAME": 0,
		"PING":      1001,
		"PONG":      1002,
	}
)

func (x CMD_GAME) Enum() *CMD_GAME {
	p := new(CMD_GAME)
	*p = x
	return p
}

func (x CMD_GAME) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMD_GAME) Descriptor() protoreflect.EnumDescriptor {
	return file_ping_proto_enumTypes[1].Descriptor()
}

func (CMD_GAME) Type() protoreflect.EnumType {
	return &file_ping_proto_enumTypes[1]
}

func (x CMD_GAME) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CMD_GAME.Descriptor instead.
func (CMD_GAME) EnumDescriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{1}
}

type G2S_DataTransfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnId uint32 `protobuf:"varint,1,opt,name=ConnId,proto3" json:"ConnId,omitempty"`
	MsgID  int32  `protobuf:"varint,2,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *G2S_DataTransfer) Reset() {
	*x = G2S_DataTransfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2S_DataTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2S_DataTransfer) ProtoMessage() {}

func (x *G2S_DataTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2S_DataTransfer.ProtoReflect.Descriptor instead.
func (*G2S_DataTransfer) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{0}
}

func (x *G2S_DataTransfer) GetConnId() uint32 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *G2S_DataTransfer) GetMsgID() int32 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *G2S_DataTransfer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type S2G_DataTransfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnId uint32 `protobuf:"varint,1,opt,name=ConnId,proto3" json:"ConnId,omitempty"`
	MsgID  int32  `protobuf:"varint,2,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *S2G_DataTransfer) Reset() {
	*x = S2G_DataTransfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2G_DataTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2G_DataTransfer) ProtoMessage() {}

func (x *S2G_DataTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2G_DataTransfer.ProtoReflect.Descriptor instead.
func (*S2G_DataTransfer) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{1}
}

func (x *S2G_DataTransfer) GetConnId() uint32 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *S2G_DataTransfer) GetMsgID() int32 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *S2G_DataTransfer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type C2S_Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping int32 `protobuf:"varint,1,opt,name=Ping,proto3" json:"Ping,omitempty"`
}

func (x *C2S_Ping) Reset() {
	*x = C2S_Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Ping) ProtoMessage() {}

func (x *C2S_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Ping.ProtoReflect.Descriptor instead.
func (*C2S_Ping) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_Ping) GetPing() int32 {
	if x != nil {
		return x.Ping
	}
	return 0
}

type S2C_Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong int32 `protobuf:"varint,2,opt,name=Pong,proto3" json:"Pong,omitempty"`
}

func (x *S2C_Pong) Reset() {
	*x = S2C_Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Pong) ProtoMessage() {}

func (x *S2C_Pong) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Pong.ProtoReflect.Descriptor instead.
func (*S2C_Pong) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_Pong) GetPong() int32 {
	if x != nil {
		return x.Pong
	}
	return 0
}

var File_ping_proto protoreflect.FileDescriptor

var file_ping_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x10,
	0x47, 0x32, 0x53, 0x5f, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x54, 0x0a, 0x10, 0x53, 0x32, 0x47, 0x5f, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d,
	0x73, 0x67, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x08, 0x43, 0x32, 0x53, 0x5f,
	0x50, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x22, 0x1e, 0x0a, 0x08, 0x53, 0x32, 0x43, 0x5f,
	0x50, 0x6f, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x2a, 0x51, 0x0a, 0x0b, 0x43, 0x4d, 0x44, 0x5f,
	0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4e, 0x49, 0x54, 0x5f,
	0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x11, 0x47, 0x32, 0x53,
	0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x45, 0x52, 0x10, 0xa3,
	0x9c, 0x01, 0x12, 0x17, 0x0a, 0x11, 0x53, 0x32, 0x47, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x54,
	0x52, 0x41, 0x4e, 0x53, 0x46, 0x45, 0x52, 0x10, 0xa4, 0x9c, 0x01, 0x2a, 0x2f, 0x0a, 0x08, 0x43,
	0x4d, 0x44, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x49, 0x54, 0x5f,
	0x47, 0x41, 0x4d, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47, 0x10, 0xe9,
	0x07, 0x12, 0x09, 0x0a, 0x04, 0x50, 0x4f, 0x4e, 0x47, 0x10, 0xea, 0x07, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ping_proto_rawDescOnce sync.Once
	file_ping_proto_rawDescData = file_ping_proto_rawDesc
)

func file_ping_proto_rawDescGZIP() []byte {
	file_ping_proto_rawDescOnce.Do(func() {
		file_ping_proto_rawDescData = protoimpl.X.CompressGZIP(file_ping_proto_rawDescData)
	})
	return file_ping_proto_rawDescData
}

var file_ping_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ping_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ping_proto_goTypes = []interface{}{
	(CMD_SERVICE)(0),         // 0: CMD_SERVICE
	(CMD_GAME)(0),            // 1: CMD_GAME
	(*G2S_DataTransfer)(nil), // 2: G2S_DataTransfer
	(*S2G_DataTransfer)(nil), // 3: S2G_DataTransfer
	(*C2S_Ping)(nil),         // 4: C2S_Ping
	(*S2C_Pong)(nil),         // 5: S2C_Pong
}
var file_ping_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ping_proto_init() }
func file_ping_proto_init() {
	if File_ping_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ping_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2S_DataTransfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ping_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2G_DataTransfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ping_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ping_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ping_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ping_proto_goTypes,
		DependencyIndexes: file_ping_proto_depIdxs,
		EnumInfos:         file_ping_proto_enumTypes,
		MessageInfos:      file_ping_proto_msgTypes,
	}.Build()
	File_ping_proto = out.File
	file_ping_proto_rawDesc = nil
	file_ping_proto_goTypes = nil
	file_ping_proto_depIdxs = nil
}
